service: hms-email-service

frameworkVersion: '>=3'

provider:
  name: aws
  runtime: python3.11
  region: ap-south-1
  environment:
    EMAIL_FROM: {your-actual-email}
    EMAIL_PASSWORD: {your-email-app-password}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    host: localhost

functions:
  sendEmail:
    handler: handler.send_notification
    events:
      - http:
          path: /send-email
          method: post
          cors: true
